[phases.setup]
cmds = ["apt-get update"]

[phases.install]
cmds = [
    "apt-get install -y php php-curl",
    "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer",
    "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "php -S 0.0.0.0:8888 index.php"