[phases.setup]
nixPkgs = ['php82', 'php82Extensions.curl', 'php82Extensions.json']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[start]
cmd = 'php -S 0.0.0.0:$PORT router.php'